In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing , model_selection , svm
from sklearn.linear_model import LinearRegression

df=pd.read_csv('day.csv')
print(df.head())

   instant    dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  01-01-11       1   0     1        0        6           0   
1        2  02-01-11       1   0     1        0        0           0   
2        3  03-01-11       1   0     1        0        1           1   
3        4  04-01-11       1   0     1        0        2           1   
4        5  05-01-11       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600  


In [7]:
df=df[['season','yr','mnth','holiday','weekday','workingday','weathersit','temp','atemp','hum','windspeed','cnt']]
print(df.head())
df.fillna(-9999,inplace=True)
df.dropna(inplace=True)
X=np.array(df.drop(['cnt'],1))
y=np.array(df['cnt'])
print(X)
print(y)

   season  yr  mnth  holiday  weekday  workingday  weathersit      temp  \
0       1   0     1        0        6           0           2  0.344167   
1       1   0     1        0        0           0           2  0.363478   
2       1   0     1        0        1           1           1  0.196364   
3       1   0     1        0        2           1           1  0.200000   
4       1   0     1        0        3           1           1  0.226957   

      atemp       hum  windspeed   cnt  
0  0.363625  0.805833   0.160446   985  
1  0.353739  0.696087   0.248539   801  
2  0.189405  0.437273   0.248309  1349  
3  0.212122  0.590435   0.160296  1562  
4  0.229270  0.436957   0.186900  1600  
[[ 1.        0.        1.       ...  0.363625  0.805833  0.160446]
 [ 1.        0.        1.       ...  0.353739  0.696087  0.248539]
 [ 1.        0.        1.       ...  0.189405  0.437273  0.248309]
 ...
 [ 1.        1.       12.       ...  0.2424    0.752917  0.124383]
 [ 1.        1.       12.     

In [9]:
X=preprocessing.scale(X)
X_train,X_test,y_train,y_test=model_selection.train_test_split(X,y,test_size=0.2)

In [18]:
clf=LinearRegression()
clf.fit(X_train,y_train)
accuracy=clf.score(X_test,y_test)
print(accuracy)

0.7610788435311665


In [14]:
clf=svm.SVR()
clf.fit(X_train,y_train)
accuracy=clf.score(X_test,y_test)
print(accuracy)

0.024231350915585037


In [15]:
clf=svm.SVR('poly')
clf.fit(X_train,y_train)
accuracy=clf.score(X_test,y_test)
print(accuracy)

0.030472029436929504
